import { useEffect, useState } from 'react';
import { ArrowDownToLine, ChevronLeft, ChevronRight, Database, Search, ShieldAlert } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { errorMessage, getEvents, getEventSummary } from '../api/client';
import type { DetectionEvent, EventSummary } from '../types';
import { EventTable } from './EventTable';
import { EventDetail } from './EventDetail';

export function EventsWorkspace({ hash }: { hash: string }) {
  const runId = new URLSearchParams(hash.split('?')[1]).get('run') || '';
  const [source, setSource] = useState(runId ? 'simulation' : ''), [severity, setSeverity] = useState(''), [review, setReview] = useState('');
  const [type, setType] = useState(''), [minutes, setMinutes] = useState(0), [ip, setIp] = useState(''), [draft, setDraft] = useState('');
  const [page, setPage] = useState(1), [refresh, setRefresh] = useState(0), [selected, setSelected] = useState<number | null>(null);
  const [rows, setRows] = useState<DetectionEvent[]>([]), [summary, setSummary] = useState<EventSummary | null>(null);
  const [total, setTotal] = useState(0), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  useEffect(() => { const timer = setInterval(() => setRefresh(v => v + 1), 5000); return () => clearInterval(timer); }, []);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true);
    const filters = { source: source || undefined, scenario_run_id: runId || undefined, severity: severity || undefined, review: review || undefined, attack_type: type || undefined, ip: ip || undefined, start_time: minutes ? new Date(Date.now() - minutes * 60000).toISOString() : undefined };
    Promise.all([getEvents({ ...filters, page, page_size: 20 }, controller.signal), getEventSummary(filters, controller.signal)])
      .then(([events, stats]) => { if (!controller.signal.aborted) { setRows(events.items); setTotal(events.total); setSummary(stats); setError(''); if (page > 1 && !events.items.length) setPage(Math.max(1, Math.ceil(events.total / 20))); } })
      .catch(e => { if (!controller.signal.aborted) setError(errorMessage(e)); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [source, severity, review, type, minutes, ip, page, refresh, runId]);
  const exportRows = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(rows, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = 'ebpf-events.json'; a.click(); URL.revokeObjectURL(url); };
  const filter = (setter: (v: string) => void) => (e: React.ChangeEvent<HTMLSelectElement>) => { setter(e.target.value); setPage(1); };
  return <div className="events-workspace"><div className="analysis-intro"><div><span className="eyebrow">PERSISTED SECURITY EVIDENCE</span><h1>탐지 이벤트</h1><p>데이터베이스에 저장된 탐지 기록을 검색하고 판단 근거를 남기세요.</p></div><span className="evidence-tag"><Database size={15}/>DB 이력 조회</span></div>
    {runId && <div className="scenario-notice"><ShieldAlert size={22}/><div><strong>시나리오 실행별 이벤트</strong><p><code>{runId}</code> <a href={`#scenarios?run=${runId}`}>실행 그래프 보기 ↗</a> · <a href="#events">전체 기록</a></p></div></div>}
    <div className="evidence-stats">{[['검색 결과', total], ['Critical', summary?.severity.critical ?? 0], ['검토 대기', summary?.is_confirmed.pending ?? 0], ['모의 이벤트', summary?.source.simulation ?? 0]].map(([label, value]) => <section className="summary-card" key={label}><span>{label}</span><strong>{Number(value).toLocaleString()}<small>건</small></strong><p>현재 검색 조건 · DB 집계</p></section>)}</div>
    {error && <div className="error-banner" role="alert">{error}<button onClick={() => setRefresh(v => v + 1)}>다시 시도</button></div>}
    <div className="event-charts"><section className="panel"><div className="panel-heading"><div><h2>탐지 타임라인</h2><p>최근 24시간 내 검색 조건 · 분당 DB 이벤트 수</p></div></div>{summary?.timeline.length ? <div className="event-history-chart" role="img" aria-label="데이터베이스 탐지 이벤트 타임라인"><ResponsiveContainer width="100%" height="100%"><BarChart data={summary.timeline}><CartesianGrid vertical={false} stroke="#edf1f6"/><XAxis dataKey="timestamp" tickFormatter={v => new Date(v).toLocaleTimeString('ko-KR', { hour: '2-digit', minute: '2-digit' })} fontSize={10} minTickGap={35}/><YAxis allowDecimals={false} width={35} fontSize={10}/><Tooltip labelFormatter={v => new Date(String(v)).toLocaleString('ko-KR')}/><Bar dataKey="count" name="탐지 이벤트" fill="#6379df" radius={[4, 4, 0, 0]} maxBarSize={35} isAnimationActive={false}/></BarChart></ResponsiveContainer></div> : <div className="panel-message">최근 24시간에 해당하는 이벤트가 없습니다.</div>}</section>
    <section className="panel"><div className="panel-heading"><div><h2>탐지 유형 분포</h2><p>현재 검색 범위 전체</p></div></div><div className="event-type-bars">{Object.entries(summary?.attack_type ?? {}).sort((a,b) => b[1]-a[1]).map(([name, count]) => <div key={name}><span>{name.replaceAll('_', ' ')}<b>{count.toLocaleString()}</b></span><i style={{ width: `${100 * count / Math.max(total, 1)}%` }}/></div>)}{!total && <p>집계할 이벤트가 없습니다.</p>}</div></section></div>
    <section className="panel events-panel"><div className="panel-heading"><div><h2>탐지 기록 <span className="count-pill">{total}</span></h2><p>LIVE와 SIMULATION 출처 및 검토 상태를 함께 확인하세요.</p></div><button className="outline-button" onClick={exportRows} disabled={loading || !rows.length}><ArrowDownToLine size={14}/>현재 페이지 내보내기</button></div>
      <div className="event-filters"><label>출처<select aria-label="이벤트 출처" value={source} onChange={filter(setSource)}><option value="">전체 출처</option><option value="live">LIVE · 실시간</option><option value="simulation">SIMULATION · 모의</option></select></label><label>심각도<select value={severity} onChange={filter(setSeverity)}><option value="">전체 심각도</option>{['critical','high','medium','low'].map(v => <option key={v}>{v}</option>)}</select></label><label>검토 상태<select aria-label="검토 상태" value={review} onChange={filter(setReview)}><option value="">전체 상태</option><option value="pending">검토 대기</option><option value="confirmed">정탐 확인</option><option value="false_positive">오탐 확인</option></select></label><label>탐지 유형<select value={type} onChange={filter(setType)}><option value="">전체 유형</option>{['SYN_FLOOD','PORT_SCAN','LARGE_FLOW','TRAFFIC_SPIKE','ANOMALY'].map(v => <option key={v}>{v}</option>)}</select></label><label>기간<select value={minutes} onChange={e => { setMinutes(Number(e.target.value)); setPage(1); }}><option value={0}>전체 기간</option><option value={60}>최근 1시간</option><option value={1440}>최근 24시간</option></select></label><form onSubmit={e => { e.preventDefault(); setIp(draft.trim()); setPage(1); }}><label>IP 주소 검색<input value={draft} onChange={e => setDraft(e.target.value)} placeholder="출발지 또는 목적지 IP"/></label><button className="outline-button" type="submit"><Search size={14}/>검색</button></form><button className="text-button" onClick={() => setRefresh(v => v + 1)}>새로고침</button></div>
      <EventTable events={rows} loading={loading} onSelect={setSelected}/><div className="pagination"><span>{total.toLocaleString()}개 기록 · {page} / {Math.max(1, Math.ceil(total/20))} 페이지</span><div><button aria-label="이전 페이지" disabled={page === 1 || loading} onClick={() => setPage(v => v-1)}><ChevronLeft size={16}/></button><button aria-label="다음 페이지" disabled={page*20 >= total || loading} onClick={() => setPage(v => v+1)}><ChevronRight size={16}/></button></div></div>
    </section>{selected !== null && <EventDetail id={selected} onClose={() => { setSelected(null); setRefresh(v => v+1); }}/>}</div>;
}
