"""initial_schema"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "423cae8d12db"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detection_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "src_ip",
            sa.String(length=45).with_variant(postgresql.INET(), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "dst_ip",
            sa.String(length=45).with_variant(postgresql.INET(), "postgresql"),
            nullable=False,
        ),
        sa.Column("src_port", sa.Integer(), nullable=False),
        sa.Column("dst_port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.Integer(), nullable=False),
        sa.Column("attack_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=8), nullable=False),
        sa.Column("anomaly_score", sa.Float(), nullable=True),
        sa.Column("pkt_rate", sa.Float(), nullable=False),
        sa.Column("byte_rate", sa.Float(), nullable=False),
        sa.Column("syn_ratio", sa.Float(), nullable=False),
        sa.Column("port_entropy", sa.Float(), nullable=False),
        sa.Column("flow_duration", sa.Float(), nullable=False),
        sa.Column(
            "raw_features",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_confirmed", sa.Boolean(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint("severity IN ('critical','high','medium','low')"),
        sa.CheckConstraint("dst_port BETWEEN 0 AND 65535"),
        sa.CheckConstraint("protocol IN (6,17)"),
        sa.CheckConstraint("src_port BETWEEN 0 AND 65535"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    op.create_index(
        op.f("ix_detection_events_attack_type"), "detection_events", ["attack_type"], unique=False
    )
    op.create_index(
        op.f("ix_detection_events_detected_at"), "detection_events", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_detection_events_severity"), "detection_events", ["severity"], unique=False
    )
    op.create_index(
        op.f("ix_detection_events_src_ip"), "detection_events", ["src_ip"], unique=False
    )
    op.create_table(
        "runtime_config",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "thresholds",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "system_metrics",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cpu_percent", sa.Float(), nullable=False),
        sa.Column("memory_percent", sa.Float(), nullable=False),
        sa.Column("ebpf_cpu_delta", sa.Float(), nullable=True),
        sa.Column("pkt_total", sa.BigInteger(), nullable=False),
        sa.Column("event_total", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_metrics_collected_at"), "system_metrics", ["collected_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_metrics_collected_at"), table_name="system_metrics")
    op.drop_table("system_metrics")
    op.drop_table("runtime_config")
    op.drop_index(op.f("ix_detection_events_src_ip"), table_name="detection_events")
    op.drop_index(op.f("ix_detection_events_severity"), table_name="detection_events")
    op.drop_index(op.f("ix_detection_events_detected_at"), table_name="detection_events")
    op.drop_index(op.f("ix_detection_events_attack_type"), table_name="detection_events")
    op.drop_table("detection_events")
    # ### end Alembic commands ###
