"""Incident response workspace, identities, durable jobs and model observations.

Additive migration; original detection events and scenario evidence are retained.
"""

import sqlalchemy as sa
from alembic import op

revision = "c87a20b1f906"
down_revision = "89c6d1e42a10"
branch_labels = depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "correlation_keys",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("touched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_throttles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "model_deployments",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("stage", sa.String(length=16), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operators",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("slack_user_id", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slack_user_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "ops_control",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kill_switch", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("address", sa.String(length=45), nullable=False),
        sa.Column("service_port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.Integer(), nullable=False),
        sa.Column("environment", sa.String(length=16), nullable=False),
        sa.Column("criticality", sa.String(length=16), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("protected_cidrs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["operators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("address", "service_port", "protocol", "environment"),
    )
    op.create_table(
        "operator_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("operator_id", sa.String(length=36), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_operator_sessions_expires_at"), "operator_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_operator_sessions_operator_id"), "operator_sessions", ["operator_id"], unique=False
    )
    op.create_table(
        "shadow_predictions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_id", sa.String(length=80), nullable=False),
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("predicted_attack", sa.Boolean(), nullable=True),
        sa.Column("rule_attack", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("feature_schema_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["model_deployments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_id", "message_id"),
    )
    op.create_index(
        op.f("ix_shadow_predictions_model_id"), "shadow_predictions", ["model_id"], unique=False
    )
    op.create_index(
        op.f("ix_shadow_predictions_observed_at"),
        "shadow_predictions",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shadow_predictions_source"), "shadow_predictions", ["source"], unique=False
    )
    op.create_table(
        "enforcement_points",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enforcement_points_asset_id"), "enforcement_points", ["asset_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("active_key", sa.String(length=64), nullable=True),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("attack_type", sa.String(length=32), nullable=False),
        sa.Column("priority", sa.String(length=2), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("scenario_run_id", sa.String(length=36), nullable=True),
        sa.Column("asset_id", sa.String(length=36), nullable=True),
        sa.Column("asset_name", sa.String(length=120), nullable=False),
        sa.Column("dst_ip", sa.String(length=45), nullable=False),
        sa.Column("dst_port", sa.Integer(), nullable=False),
        sa.Column("protocol", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("event_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recovering_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ack_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("escalated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["operators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scenario_run_id"],
            ["scenario_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("active_key"),
    )
    op.create_index(op.f("ix_incidents_created_at"), "incidents", ["created_at"], unique=False)
    op.create_index(op.f("ix_incidents_priority"), "incidents", ["priority"], unique=False)
    op.create_index(op.f("ix_incidents_source"), "incidents", ["source"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "action_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("requester_id", sa.String(length=36), nullable=False),
        sa.Column("approver_id", sa.String(length=36), nullable=True),
        sa.Column("point_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("incident_version", sa.Integer(), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("preview", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["operators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["enforcement_points.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["operators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_action_requests_incident_id"), "action_requests", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_action_requests_status"), "action_requests", ["status"], unique=False)
    op.create_table(
        "audit_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("actor_name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["operators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_entries_created_at"), "audit_entries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_entries_incident_id"), "audit_entries", ["incident_id"], unique=False
    )
    op.create_table(
        "incident_events",
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["detection_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("incident_id", "event_id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("dedupe_key", sa.String(length=180), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("channel", sa.String(length=16), nullable=False),
        sa.Column("destination", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_id", sa.String(length=120), nullable=True),
        sa.Column("last_error", sa.String(length=240), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key"),
    )
    op.create_index(
        op.f("ix_notification_deliveries_incident_id"),
        "notification_deliveries",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_next_attempt_at"),
        "notification_deliveries",
        ["next_attempt_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_deliveries_status"),
        "notification_deliveries",
        ["status"],
        unique=False,
    )
    op.create_table(
        "service_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("point_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("healthy", sa.Boolean(), nullable=False),
        sa.Column("success_rate", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("ingress_pps", sa.Float(), nullable=False),
        sa.Column("policy_hits", sa.BigInteger(), nullable=False),
        sa.Column("normal_sessions", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["enforcement_points.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_observations_observed_at"),
        "service_observations",
        ["observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_observations_point_id"), "service_observations", ["point_id"], unique=False
    )
    op.create_table(
        "action_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("incident_id", sa.String(length=36), nullable=False),
        sa.Column("point_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("policy", sa.JSON(), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("command_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoke_requested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_result", sa.JSON(), nullable=False),
        sa.Column("last_error", sa.String(length=240), nullable=True),
        sa.Column("last_report_seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["point_id"],
            ["enforcement_points.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["action_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.create_index(
        op.f("ix_action_runs_incident_id"), "action_runs", ["incident_id"], unique=False
    )
    op.create_index(op.f("ix_action_runs_point_id"), "action_runs", ["point_id"], unique=False)
    op.create_index(op.f("ix_action_runs_status"), "action_runs", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_action_runs_status"), table_name="action_runs")
    op.drop_index(op.f("ix_action_runs_point_id"), table_name="action_runs")
    op.drop_index(op.f("ix_action_runs_incident_id"), table_name="action_runs")
    op.drop_table("action_runs")
    op.drop_index(op.f("ix_service_observations_point_id"), table_name="service_observations")
    op.drop_index(op.f("ix_service_observations_observed_at"), table_name="service_observations")
    op.drop_table("service_observations")
    op.drop_index(op.f("ix_notification_deliveries_status"), table_name="notification_deliveries")
    op.drop_index(
        op.f("ix_notification_deliveries_next_attempt_at"), table_name="notification_deliveries"
    )
    op.drop_index(
        op.f("ix_notification_deliveries_incident_id"), table_name="notification_deliveries"
    )
    op.drop_table("notification_deliveries")
    op.drop_table("incident_events")
    op.drop_index(op.f("ix_audit_entries_incident_id"), table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_created_at"), table_name="audit_entries")
    op.drop_table("audit_entries")
    op.drop_index(op.f("ix_action_requests_status"), table_name="action_requests")
    op.drop_index(op.f("ix_action_requests_incident_id"), table_name="action_requests")
    op.drop_table("action_requests")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_source"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_priority"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_created_at"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_enforcement_points_asset_id"), table_name="enforcement_points")
    op.drop_table("enforcement_points")
    op.drop_index(op.f("ix_shadow_predictions_source"), table_name="shadow_predictions")
    op.drop_index(op.f("ix_shadow_predictions_observed_at"), table_name="shadow_predictions")
    op.drop_index(op.f("ix_shadow_predictions_model_id"), table_name="shadow_predictions")
    op.drop_table("shadow_predictions")
    op.drop_index(op.f("ix_operator_sessions_operator_id"), table_name="operator_sessions")
    op.drop_index(op.f("ix_operator_sessions_expires_at"), table_name="operator_sessions")
    op.drop_table("operator_sessions")
    op.drop_table("assets")
    op.drop_table("ops_control")
    op.drop_table("operators")
    op.drop_table("model_deployments")
    op.drop_table("login_throttles")
    op.drop_table("correlation_keys")
    # ### end Alembic commands ###
