import { test, expect } from '@playwright/test';

test('full-week evidence, model comparison and legacy context availability', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const analysis = await (await request.get('/api/analysis/model')).json();
  expect(analysis.context_evaluation.deployment_approved).toBe(false);
  expect(analysis.context_evaluation.candidates).toHaveLength(5);
  await page.goto('/#capture');
  await expect(page.locator('.dataset-day')).toHaveCount(5);
  await expect(page.locator('.benchmark-coverage')).toContainText('4 / 14종');
  await expect(page.locator('.benchmark-coverage')).toContainText('시험에 없는 유형');
  await page.getByLabel('캡처 파일').selectOption('Monday-WorkingHours.pcap');
  await expect(page.locator('.label-bars')).toContainText('BENIGN');
  await expect(page.locator('.label-row')).toHaveCount(1);
  await expect(page.locator('.evidence-panel')).toContainText('1초 불확실성');
  await page.getByLabel('비교 모델').selectOption('if_25');
  const candidate = analysis.context_evaluation.candidates.find((item: { id: string }) => item.id === 'if_25');
  await expect(page.locator('.benchmark-metrics')).toContainText(`${(candidate.performance.f1 * 100).toFixed(2)}%`);
  await page.getByRole('button', { name: '지도학습 · 25개', exact: true }).click();
  await expect(page.getByLabel('비교 모델')).toHaveValue('hgb_25');
  await page.getByText('유형별 표본·미탐·오탐 확인', { exact: true }).click();
  await expect(page.locator('.benchmark-label-details')).toContainText('BENIGN · 탐지는 오탐');
  const pending = page.waitForEvent('download');
  await page.getByRole('button', { name: '실험 보고서', exact: true }).click();
  expect((await pending).suggestedFilename()).toBe('context-feature-benchmark.json');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.locator('.benchmark-panel').screenshot({ path: `test-results/benchmark-${test.info().project.name}.png` });
  await page.goto('/#overview');
  await page.getByRole('button', { name: '이벤트 25 상세 보기' }).click();
  await page.getByText('목적지·양방향 탐지 근거', { exact: true }).click();
  await expect(page.getByRole('dialog')).toContainText('이 기록은 이전 Collector 피처입니다');
  expect(errors).toEqual([]);
});

test('filters, pagination, detail, export and capture selection', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '네트워크 대시보드' })).toBeVisible();
  await expect(page.locator('.pagination')).toContainText('25개 기록');
  await page.getByRole('button', { name: '다음 페이지' }).click();
  await expect(page.locator('.pagination')).toContainText('2 / 2');
  await expect(page.locator('tbody tr')).toHaveCount(5);
  await page.getByLabel('탐지 유형', { exact: true }).selectOption('PORT_SCAN');
  await expect(page.locator('.pagination')).toContainText('4개 기록');
  await expect(page.locator('tbody tr')).toHaveCount(4);
  await page.getByRole('button', { name: '이벤트 25 상세 보기' }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog')).toContainText('192.0.2.1:5024');
  await expect(page.getByRole('dialog')).toContainText('미제공 (규칙 기반)');
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: '현재 페이지 내보내기' }).click();
  expect((await download).suggestedFilename()).toBe('ebpf-events.json');
  await page.getByLabel('심각도', { exact: true }).selectOption('low');
  await expect(page.locator('.pagination')).toContainText('0개 기록');
  await expect(page.getByText('조건에 맞는 탐지 이벤트가 없습니다.')).toBeVisible();
  await page.goto('/#capture');
  await expect(page.getByLabel('캡처 파일')).toBeVisible();
  await page.getByLabel('캡처 파일').selectOption('Thursday-WorkingHours.pcap');
  await expect(page.locator('#capture')).toContainText('정답 레이블 분포');
  await expect(page.locator('#capture')).toContainText('전체 파일 분석');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: `test-results/dashboard-${test.info().project.name}.png`, fullPage: true });
  expect(errors).toEqual([]);
});

test('threshold authentication, persistence and chart threshold', async ({ page, request }) => {
  const original = await (await request.get('/api/config/thresholds')).json();
  try {
    await page.goto('/#settings');
    await page.getByLabel('ML 이상 점수 임계값').fill('-0.2');
    await page.getByLabel('관리자 토큰').fill('incorrect');
    await page.getByRole('button', { name: '임계값 저장' }).click();
    await expect(page.locator('#settings [role=alert]')).toContainText('Administrator token required');
    await page.getByLabel('관리자 토큰').fill('browser-admin');
    await page.getByRole('button', { name: '임계값 저장' }).click();
    await expect(page.getByText('탐지 임계값을 저장했습니다.')).toBeVisible();
    await expect(page.getByLabel('관리자 토큰')).toHaveValue('');
    expect(await page.evaluate(() => JSON.stringify(localStorage))).not.toContain('browser-admin');
    await page.reload();
    await expect(page.getByLabel('ML 이상 점수 임계값')).toHaveValue('-0.2');
    await page.goto('/#overview');
    await expect(page.getByText('임계값 -0.2', { exact: true })).toBeVisible();
  } finally {
    await request.put('/api/config/thresholds', { data: original, headers: { Authorization: 'Bearer browser-admin' } });
  }
});

test('API error recovery and websocket reconnect restore events', async ({ page }) => {
  let failed = true;
  await page.route('**/api/events?**', route => failed ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: '테스트 연결 오류' } }) }) : route.continue());
  await page.goto('/');
  await expect(page.getByRole('alert').filter({ hasText: '테스트 연결 오류' })).toBeVisible();
  failed = false;
  await page.getByRole('button', { name: '다시 시도' }).first().click();
  await expect(page.locator('.pagination')).toContainText('25개 기록');
  await expect(page.getByText('실시간 연결됨', { exact: true })).toBeVisible();
  await page.context().setOffline(true);
  await expect(page.locator('.connection')).not.toHaveText('실시간 연결됨', { timeout: 15000 });
  await page.context().setOffline(false);
  await expect(page.getByText('실시간 연결됨', { exact: true })).toBeVisible({ timeout: 15000 });
  await expect(page.locator('tbody tr')).toHaveCount(20);
});


test('analysis evidence, capture switching, download and navigation', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/#capture');
  await expect(page.getByRole('heading', { name: 'CIC-IDS-2017 분석 워크스페이스' })).toBeVisible();
  await expect(page.locator('.capture-stats')).toContainText('3,357,642');
  await expect(page.locator('.label-bars')).toContainText('DDoS');
  await expect(page.locator('.model-runtime')).toContainText('현재 운영 엔진: 규칙 기반');
  await expect(page.locator('.evaluation-status')).toContainText('운영 미승인');
  await page.getByLabel('캡처 파일').selectOption('Thursday-WorkingHours.pcap');
  await expect(page.locator('.capture-stats')).toContainText('2,599,785');
  await expect(page.locator('.label-bars')).toContainText('Infiltration');
  await expect(page.locator('.label-bars')).not.toContainText('DDoS');
  const pending = page.waitForEvent('download');
  await page.getByRole('button', { name: '분석 JSON' }).click();
  const download = await pending;
  expect(download.suggestedFilename()).toBe('Thursday-WorkingHours-analysis.json');
  const stream = await download.createReadStream();
  let body = '';
  for await (const chunk of stream!) body += chunk;
  const exported = JSON.parse(body);
  expect(exported.capture.source).toBe('Thursday-WorkingHours.pcap');
  expect(exported.capture.labels.counts.matched).toBe(2170602);
  expect(exported.capture.labels.alignment.capture_sha256).toBe(exported.capture.sha256);
  expect(exported.model.evaluation.deployment_approved).toBe(false);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: `test-results/analysis-${test.info().project.name}.png`, fullPage: true });
  expect(errors).toEqual([]);
});

test('IP search, reset and independent analysis error recovery', async ({ page }) => {
  await page.goto('/');
  await page.getByLabel('IP 주소 검색').fill('192.0.2.99');
  await page.getByRole('button', { name: '검색', exact: true }).click();
  await expect(page.locator('.pagination')).toContainText('0개 기록');
  await page.getByRole('button', { name: '초기화', exact: true }).click();
  await expect(page.locator('.pagination')).toContainText('25개 기록');
  await page.getByLabel('IP 주소 검색').fill('192.0.2.2');
  await page.getByRole('button', { name: '검색', exact: true }).click();
  await expect(page.locator('.pagination')).toContainText('25개 기록');
  let failed = true;
  await page.route('**/api/analysis/model', route => failed ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: '평가 조회 테스트 오류' } }) }) : route.continue());
  await page.goto('/#capture');
  await expect(page.locator('.model-panel [role=alert]')).toContainText('평가 조회 테스트 오류');
  await expect(page.locator('.label-bars')).toContainText('DDoS');
  failed = false;
  await page.locator('.model-panel').getByRole('button', { name: '다시 시도' }).click();
  await expect(page.locator('.evaluation-metrics')).toBeVisible();
});

test('scenario execution persists graphs, isolates live traffic and links reviewed DB events', async ({ page }) => {
  test.setTimeout(45000);
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto('/#scenarios');
  await expect(page.getByRole('heading', { name: '탐지 시나리오', exact: true })).toBeVisible();
  await page.getByLabel('관리자 토큰', { exact: true }).fill('browser-admin');
  await page.getByRole('button', { name: '침입 탐지 리허설 실행' }).click();
  await expect(page.locator('.run-status')).toHaveText('완료', { timeout: 22000 });
  await expect(page.locator('.run-stats')).toContainText('15');
  await expect(page.getByLabel('관리자 토큰', { exact: true })).toHaveValue('');
  const runId = await page.locator('.run-title code').innerText();
  await page.reload();
  await expect(page.locator('.run-title code')).toHaveText(runId);
  await expect(page.locator('.run-stats')).toContainText('15');
  await expect(page.locator('.scenario-timeline .recorded')).toHaveCount(5);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: `test-results/scenarios-${test.info().project.name}.png`, fullPage: true });
  await page.getByRole('link', { name: '탐지 이벤트에서 보기' }).click();
  await expect(page.getByRole('heading', { name: '탐지 이벤트', exact: true })).toBeVisible();
  await expect(page.locator('.pagination')).toContainText('9개 기록');
  await expect(page.locator('tbody tr')).toHaveCount(9);
  await expect(page.locator('.event-history-chart')).toBeVisible();
  await page.getByRole('button', { name: /이벤트 .* 상세 보기/ }).first().click();
  await expect(page.getByRole('dialog')).toContainText('SIMULATION · 모의 탐지');
  await page.getByLabel('판정', { exact: true }).selectOption('confirmed');
  await page.getByLabel('검토 메모').fill('시나리오 단계와 탐지 근거 일치');
  await page.getByLabel('검토용 관리자 토큰').fill('browser-admin');
  await page.getByRole('button', { name: '검토 저장', exact: true }).click();
  await expect(page.getByText('검토 결과를 저장했습니다.')).toBeVisible();
  await page.getByRole('button', { name: '상세 닫기' }).click();
  await page.getByLabel('검토 상태', { exact: true }).selectOption('confirmed');
  await expect(page.locator('.pagination')).toContainText('1개 기록');
  await page.reload();
  await expect(page.locator('tbody')).toContainText('정탐 확인');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: `test-results/events-${test.info().project.name}.png`, fullPage: true });
  await page.goto('/#overview');
  await expect(page.locator('.pagination')).toContainText('25개 기록');
  expect(errors).toEqual([]);
});
